### ISSUE TITLE
[FEAT] Firebase Budget View

### ISSUE THREAD

**Issue by JungDohyeon** [JungDohyeon/MC3-Team14-FutureStarz#108]
## 📌  Description

- Firebase Budget 기능 저장

## 📝  To-do

- [ ] Store Firebase income
- [ ] Store Firebase spend
- [ ] Store Firebase account
- [ ] Store Firebase post
- [ ] Read Firebase income
- [ ] Read Firebase spend
- [ ] Read Firebase account
- [ ] Read Firebase post
