### ISSUE TITLE
[FEAT] Add Category Analysis Firebase

### ISSUE THREAD

**Issue by juwonleee** [JungDohyeon/MC3-Team14-FutureStarz#117]
## 📌  Description
전체 지출 분석 파이어베이스에서 데이터 넘겨오기

## 📝  To-do
AnalysisView
- [ ] 카테고리 이름 받아오기
- [ ] 카테고리 총 금액 받아오기
- [ ] 전체 소비 원 그래프 데이터에 적용하기
- [ ] 카테고리 top 1~3 이름 받아오기
- [ ] 카테고리 top 1~3 각각 가격 받아오기

CategoryListView
- [ ] 카테고리 아이콘 
- [ ] 카테고리 이름 
- [ ] 퍼센테지 
- [ ] 카테고리 총 금액

CategoryHistoryView
- [ ] 현재 월 받아오기
- [ ] 카테고리 아이콘 (L)
- [ ] 카테고리별 총 소비 가격
- [ ] 카테고리별 총 소비 횟수
- [ ] 카테고리별 날짜 상세 내역
