### ISSUE TITLE
[DESIGN] Chore SettingView & OnboardingView

### ISSUE THREAD

**Issue by sohnseoyeon** [JungDohyeon/MC3-Team14-FutureStarz#140]
## 📌  Description
온보딩, 설정 뷰 디자인 수정

## 📝  To-do

- [ ] 온보딩 <SeletingBank> 텍스트 변경
- [ ] 설정 <SettingBankModal> section 배경색 변경
- [ ] 설정 <SettingBankModal> 텍스트 변경
