### ISSUE TITLE
[FEAT] Make AddModalView UI

### ISSUE THREAD

**Issue by sohnseoyeon** [JungDohyeon/MC3-Team14-FutureStarz#23]
## 📌  Description
가계부 메인화면에서 "추가"버튼을 눌렀을 때 나오는 모달 화면

## 📝  To-do
- [x] 거래 유형에 따른 하단 항목 변경
- [x] 날짜 선택
- [x] 금액 입력
- [x] 금액 입력 시 숫자 키패드
- [x] 카테고리 시트 선택
- [x] 내용 입력
- [ ] 내용 입력 시 글자 수 제한
- [x] 과소비 체크
- [x] 그룹원 공개 체크
- [ ] 은행 열기
