### ISSUE TITLE
[CHORE] Chore Group View

### ISSUE THREAD

**Issue by JungDohyeon** [JungDohyeon/MC3-Team14-FutureStarz#46]
## 📌  Description

그룹방 뷰 기능 명세 놓친 부분 수정

## 📝  To-do

- [x] 최대인원 (2명부터 10명) -> 초기값 세팅 필요
- [x] 토글 → 비밀번호 활성화 (쓴 칸은 모두 활성화)
- [x] 그룹 생성 창 들어가자마자 그룹이름 필드에 Focus
- [x] 각 필드 클릭 시 밑줄 색 활성화 (Main color)
- [x] 목표 금액 9자리 제한
- [ ] 목표 금액 뒤에 "원" fix
- [ ] 목표 인원 선택 -> 언더바 활성화
