### ISSUE TITLE
[DESIGN] AddModalView & SmallButton Component

### ISSUE THREAD

**Issue by sohnseoyeon** [JungDohyeon/MC3-Team14-FutureStarz#48]
## 📌  Description
AddModalView와 SmallButton Component 디자인 디테일 수정

## 📝  To-do
- [x] AddModalView - 배경색 지정
- [x] BreakdownWriting - 사용되지 않는 코드 삭제
- [x] SmallButton - 버튼 배경색 변경
- [x] SmallButton - 폰트 스타일 변경
