### ISSUE TITLE
[CHORE] Chore MainHistory View

### ISSUE THREAD

**Issue by juwonleee** [JungDohyeon/MC3-Team14-FutureStarz#56]
## 📌  Description
메인 내역 뷰 UI 디자인에 맞게 수정

## 📝  To-do

- [ ] 추가 버튼 action -> 내역 추가 모달 뷰 띄우기
- [ ] 추가 버튼 색&글꼴 수정
- [ ] 과소비 태그 다음 비공개 태그
- [ ] 스크롤 했을 시 월 고정, 내역 고정, 탭뷰 고정된 채 스크롤
