### ISSUE TITLE
[FEAT] Add Firebase Query

### ISSUE THREAD

**Issue by JungDohyeon** [JungDohyeon/MC3-Team14-FutureStarz#60]
## 📌  Description

Firebase 데이터 관리

## 📝  To-do

- [ ] Firebase Reference 확인
- [ ] Firebase Data Read
- [ ] Firebase Data Write
- [ ] 현재 로그인한 사람 정보 확인을 통한 그룹 뷰 띄울 창 구현
