### ISSUE TITLE
[FEAT] Add Firebase and Fix MainBudgetView

### ISSUE THREAD

**Issue by juwonleee** [JungDohyeon/MC3-Team14-FutureStarz#90]
## 📌  Description
메인 가계부 뷰 수정 및 파베 연결

## 📝  To-do
- [ ] 달 이동
- [ ] 목표 예산 금액 온보딩에서 받아오기
- [ ] 오늘까지 쓴 금액 합산해서 값 받아오기 
- [ ] 오늘까지 쓴 금액 그래프에 반영
- [ ] 목표 예산 금액 온보딩에서 받아온 값 입력 
- [ ] 목표 예산 그래프에 반영
- [ ] 닉넨임 받아오기
- [ ] 지출 구분해서 받아오기
- [ ] 수입 구분해서 받아오기
- [ ] 남은 금액 (수입 - 지출) 계산해서 받아오기
- [ ] 내역 날짜순으로 받아오기
- [ ] [내역] 날짜(일, 요일) 받아오기
- [ ] [내역] 하루 총 지출, 수입 구분해서 받아오기
- [ ] [내역] 한 개의 내역에 정보 나열하기 (카테고리, 가격-수입/지출 구분해서, 내용, 과소비 여부, 비공개 여부)
